start:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: select
          integration: motionblinds_rs485
    scene:
      required: true
      selector:
        select:
         options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15